2019-03-10 18:43:04,024 ERROR: Exception on /reset_password_request [POST] [in C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 192, in send
    message.rcpt_options)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 852, in sendmail
    self.ehlo_or_helo_if_needed()
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 600, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 440, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\cheon\PycharmProjects\microblog\app.py", line 126, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\cheon\PycharmProjects\microblog\static\email.py", line 22, in send_password_reset_email
    user=user, token=token))
  File "C:\Users\cheon\PycharmProjects\microblog\static\email.py", line 11, in send_email
    mail.send(msg)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 984, in quit
    res = self.docmd("quit")
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2019-03-10 18:43:57,632 INFO: Microblog startup [in C:\Users\cheon\PycharmProjects\microblog\app.py:48]
2019-03-10 18:44:06,621 ERROR: Exception on /reset_password_request [POST] [in C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 427, in send
    connection.send(self)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 192, in send
    message.rcpt_options)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 852, in sendmail
    self.ehlo_or_helo_if_needed()
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 600, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 440, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\cheon\PycharmProjects\microblog\app.py", line 126, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\cheon\PycharmProjects\microblog\static\email.py", line 22, in send_password_reset_email
    user=user, token=token))
  File "C:\Users\cheon\PycharmProjects\microblog\static\email.py", line 11, in send_email
    mail.send(msg)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 492, in send
    message.send(connection)
  File "C:\Users\cheon\PycharmProjects\microblog\venv\lib\site-packages\flask_mail.py", line 152, in __exit__
    self.host.quit()
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 984, in quit
    res = self.docmd("quit")
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 420, in docmd
    self.putcmd(cmd, args)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 367, in putcmd
    self.send(str)
  File "C:\Users\cheon\AppData\Local\Programs\Python\Python37-32\lib\smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first
2019-03-10 18:44:58,157 INFO: Microblog startup [in C:\Users\cheon\PycharmProjects\microblog\app.py:48]
2019-03-10 18:49:20,383 INFO: Microblog startup [in C:\Users\cheon\PycharmProjects\microblog\app.py:48]
